# Generated by Django 5.0.6 on 2024-12-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_garbagecollectionrequests_collection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_category', models.CharField(max_length=255)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight of Garbage (kg)')),
            ],
        ),
    ]
