# Generated by Django 5.0.6 on 2024-12-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_garbagevault'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagevault',
            name='vault_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
